#!/bin/sh
## brainageR software, global wrapper script
## James Cole, King's College London james.cole@kcl.ac.uk
## software version 2.0 24 Sep 2019

usage() {
    cat <<EOF

brainageR software version 2.0 24 Sep 2019

Required arguments: 
	-f: input Nifti file
	-o: output csv filename

Optional arguments:
	-d: debug mode - turns off clean-up
	-h: displays this help message

For example:
brainageR -f subj01_T1.nii -o subj01_brain_predicted.age.csv

Dependencies:
R packages: kernlab, RNifti, stringr
SPM (MATLAB)
FSL (for slicesdir)

EOF
    exit 1
}

############################################################################

while getopts ":f:o:dh:" opt; do
    case "${opt}" in
        f)  	nifti_file=${OPTARG} ;;
        o)		output_filename=${OPTARG} ;;
        d)		debug_mode=1 ;;
        h|*)    usage ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${nifti_file}" ] || [ -z "${output_filename}" ]; then
    usage
fi

## check files are uncompressed NIFTI fortmat
if [[ $nifti_file != *.nii ]]; then usage; fi
## check software environment and attempt to load using module
## CONFIGURE FOR YOUR LOCAL SYSTEM
for software in R matlab fsl; do
	software_check=`type $software | grep -o bin`
	if [ ! $software_check == "bin" ]; then module load $software; fi
	software_check2=`type $software | grep -o bin`
	if [ ! $software_check2 == "bin" ]; then echo $software not found; exit 1; fi
done
## software directories for your local system
brainageR_dir=/home/jcole/Work/Brain\ ageing/brainageR
spm_dir=/usr/local/spm12/
matlab_path=/usr/local/bin/matlab
FSLDIR=/usr/local/fsl/
## run brainageR analysis
cmd="$matlab_path -nosplash -nodesktop -r \"addpath(['$brainageR_dir','/software/']);spm_preprocess_brainageR('$nifti_file',['$brainageR_dir','/software/templates/'], '$spm_dir');exit\""
eval ${cmd}
readlink -f smwc1${nifti_file} > /tmp/smwc1${nifti_file%.nii}.txt
readlink -f smwc2${nifti_file} > /tmp/smwc2${nifti_file%.nii}.txt
readlink -f smwc3${nifti_file} > /tmp/smwc3${nifti_file%.nii}.txt
## generate QC images and html file
bash "$brainageR_dir"/software/slicesdir.brainageR -n ${nifti_file%.nii} [c,s]*[1,2,3]*${nifti_file}
## generate predictions
Rscript "$brainageR_dir"/software/predict_new_data_gm_wm_csf.R "${brainageR_dir}" /tmp/smwc1${nifti_file%.nii}.txt /tmp/smwc2${nifti_file%.nii}.txt /tmp/smwc3${nifti_file%.nii}.txt "${brainageR_dir}"/software/GPR_model_gm_wm_csf.RData $output_filename
## clean up
if [ -z $debug_mode ]; then
for img in c1 c2 c3 rc1 rc2 rc3 u_rc1 smwc1 smwc2 smwc3; do
	rm ${img}${nifti_file}
done
rm ${nifti_file%.nii}*seg8.mat
fi
